//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportPractice.Models
{
    using System;

    public partial class Stock
    {
        public int Id { get; set; }
        public DateTime StockDate { get; set; }
        public int Quantity { get; set; }
        public string StockStatus { get; set; }
        public int ItemID { get; set; }
    }
}
